# Generated by Django 3.0.1 on 2020-01-01 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_files', models.FileField(blank=True, upload_to='files_upload/')),
            ],
            options={
                'ordering': ('-upload_date',),
            },
        ),
    ]
