# Generated by Django 3.0 on 2019-12-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qu_step3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('user_input_text', models.CharField(max_length=100)),
                ('detected_intent', models.CharField(max_length=255)),
                ('detected_intent_confidence', models.CharField(max_length=255)),
                ('chatbot_output_text', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
